INSERT INTO municipalities (name_el, name_en, name_de, email_official) VALUES
('Δήμος Αβδήρων', '', '', 'info@avdera.gr'),
('Δήμος Αγαθονησίου', '', '', 'k.agathonisiou@kep.gov.gr'),
('Δήμος Αγιάς', '', '', 'mayordagias@0559.syzefxis.gov.gr'),
('Δήμος Αγίας Βαρβάρας', '', '', 'grdim@agiavarvara.gr'),
('Δήμος Αγίας Παρασκευής', '', '', 'dimos@agiaparaskevi.gr'),
('Δήμος Αγίου Βασιλείου', '', '', 'dimoslam@otenet.gr'),
('Δήμος Αγίου Δημητρίου', '', '', 'dad-may@dad.gr'),
('Δήμος Αγίου Ευστρατίου', '', '', 'aistratis@altecnet.gr'),
('Δήμος Αγίου Νικολάου', '', '', 'grafdim@yahoo.gr'),
('Δήμος Αγίων Αναργύρων - Καματερού', '', '', 'agiianargirinas@0087.syzefxis.gov.gr'),
('Δήμος Αγκιστρίου', '', '', 'kagistri@otenet.gr'),
('Δήμος Αγράφων', '', '', 'info@agrafa.gr'),
('Δήμος Αγρινίου', '', '', 'dimarxos@agrinio.gr'),
('Δήμος Αθηναίων', '', '', 'mayor@athens.gr'),
('Δήμος Αιγάλεω', '', '', 'egaleo@egaleo.gr'),
('Δήμος Αιγιαλείας', '', '', 'admin@aigialeia.gov.gr'),
('Δήμος Αίγινας', '', '', 'grafeiodimarxou@aeginadimos.gr'),
('Δήμος Ακτίου-Βόνιτσας', '', '', 'anact@otenet.gr'),
('Δήμος Αλεξάνδρειας', '', '', 'info@alexandria.gr'),
('Δήμος Αλεξανδρούπολης', '', '', 'dimarxos@alexpolis.gr'),
('Δήμος Αλιάρτου - Θεσπιέων', '', '', 'aliartos@otenet.gr'),
('Δήμος Αλίμου', '', '', 'info@alimos.gr'),
('Δήμος Αλμυρού', '', '', 'gram.dhmarxou@almiros.gr'),
('Δήμος Αλμωπίας', '', '', 'syzefxis@0598.syzefxis.gov.gr'),
('Δήμος Αλοννήσου', '', '', 'dimosalo@otenet.gr'),
('Δήμος Αμαρίου', '', '', 'info@amario.com.gr'),
('Δήμος Αμαρουσίου', '', '', 'dimarxos@maroussi.gr'),
('Δήμος Αμοργού', '', '', 'amorgos@aigaio.gr'),
('Δήμος Αμπελοκήπων-Μενεμένης', '', '', 'info@ampelokipi-menemeni.gr'),
('Δήμος Αμυνταίου', '', '', 'dimarxos@amyntaio.gr'),
('Δήμος Αμφίκλειας-Ελάτειας', '', '', 'info@dimos-amfiklias-elatias.gr'),
('Δήμος Αμφιλοχίας', '', '', 'dimamfil@otenet.gr'),
('Δήμος Αμφίπολης', '', '', 'info@dimos-amfipolis.gr'),
('Δήμος Ανατολικής Μάνης', '', '', 'dimarxos@1315.syzefxis.gov.gr'),
('Δήμος Ανατολικής Σάμου', '', '', 'news@vathi.gr'),
('Δήμος Ανάφης', '', '', 'k-anafis@otenet.gr'),
('Δήμος Ανδραβίδας - Κυλλήνης', '', '', 'dlehena@yahoo.gr'),
('Δήμος Ανδρίτσαινας - Κρεστένων', '', '', 'dkresten@otenet.gr'),
('Δήμος Άνδρου', '', '', 'dimos@andros.gr'),
('Δήμος Αντιπάρου', '', '', 'k.antiparou@kep.gov.gr'),
('Δήμος Ανωγείων', '', '', 'info@anogeia.gr'),
('Δήμος Αποκορώνου', '', '', 'info@apokoronas.gov.gr'),
('Δήμος Αργιθέας', '', '', 'd.argitheas@kep.gov.gr'),
('Δήμος Αργοστολίου', '', '', 'dimarxos_arg@kefallonia.gov.gr'),
('Δήμος Άργους - Μυκηνών', '', '', 'dimos@argos.gr'),
('Δήμος Άργους Ορεστικού', '', '', 'info@argosorestiko.gr'),
('Δήμος Αριστοτέλη', '', '', 'dhmstaka@otenet.gr'),
('Δήμος Αρριανών', '', '', 'filyra@0924.syzefxis.gov.gr'),
('Δήμος Αρταίων', '', '', 'dimos@arta.gr'),
('Δήμος Αρχαίας Ολυμπίας', '', '', 'dolympia@otenet.gr')
ON CONFLICT DO NOTHING;