INSERT INTO municipalities (name_el, name_en, name_de, email_official) VALUES
('Δήμος Αρχανών - Αστερουσίων', '', '', 'info@0470.syzefxis.gov.gr'),
('Δήμος Ασπροπύργου', '', '', 'grafeiodimarxou@aspropyrgos.gr'),
('Δήμος Αστυπάλαιας', '', '', 'astypalaia@astypalaia.gr'),
('Δήμος Αχαρνών', '', '', 'grdhm1@acharnes.gr'),
('Δήμος Βάρης - Βούλας - Βουλιαγμένης', '', '', 'info@vvv.gov.gr'),
('Δήμος Βελβεντού', '', '', 'grammatia@velvento.gr'),
('Δήμος Βέλου-Βόχας', '', '', 'masouri@vochas.gov.gr'),
('Δήμος Βέροιας', '', '', 'dimosverias@veria.gr'),
('Δήμος Βιάννου', '', '', 'dviannos@otenet.gr'),
('Δήμος Βισαλτίας', '', '', 'dnigr622@otenet.gr'),
('Δήμος Βοΐου', '', '', 'dimos_siatista@yahoo.gr'),
('Δήμος Βόλβης', '', '', 'dimos@dimosvolvis.gr'),
('Δήμος Βόρειας Κέρκυρας', '', '', 'info@1354.syzefxis.gov.gr'),
('Δήμος Βορείων Τζουμέρκων', '', '', 'info@voreiatzoumerka.gr'),
('Δήμος Βριλησσίων', '', '', 'noni@vrilissia.gr'),
('Δήμος Βύρωνος', '', '', 'dimarxos@dimosbyrona.gr'),
('Δήμος Γαλατσίου', '', '', 'info@galatsi.gr'),
('Δήμος Γαύδου', '', '', 'dimos@gavdos.gr'),
('Δήμος Γεωργίου Καραϊσκάκη', '', '', 'dgk1@otenet.gr'),
('Δήμος Γλυφάδας', '', '', 'grammateia@0114.syzefxis.gov.gr'),
('Δήμος Γόρτυνας', '', '', 'gortyna@in.gr'),
('Δήμος Γορτυνίας', '', '', 'ddimitsa@otenet.gr'),
('Δήμος Γρεβενών', '', '', 'dimosgrevenon@0641.syzefxis.gov.gr'),
('Δήμος Δάφνης - Υμηττού', '', '', 'dafni05@otenet.gr'),
('Δήμος Δέλτα', '', '', 'grammateia@dimosdelta.gr'),
('Δήμος Δελφών', '', '', 'dimarxos@delphi.gov.gr'),
('Δήμος Δεσκάτης', '', '', 'dimosdes@otenet.gr'),
('Δήμος Διδυμοτείχου', '', '', 'mayor@didymoteicho.gr'),
('Δήμος Διονύσου', '', '', 'secretary@agstefanos.gr'),
('Δήμος Δίου-Ολύμπου', '', '', 'dimos@dion-olympos.gr'),
('Δήμος Διρφύων-Μεσσαπίων', '', '', 'messapia@otenet.gr'),
('Δήμος Διστόμου-Αράχοβας-Αντίκυρας', '', '', 'info@daa.gov.gr'),
('Δήμος Δομοκού', '', '', 'info@domokos.gr'),
('Δήμος Δοξάτου', '', '', 'dimarxos@doxato.gr'),
('Δήμος Δράμας', '', '', 'dhmos-dramas@dra.forthnet.gr'),
('Δήμος Δυτικής Αχαΐας', '', '', 'mayor@dimosdymaion.gov.gr'),
('Δήμος Δυτικής Λέσβου', '', '', 'grafeiodimarxou@mwlesvos.gr'),
('Δήμος Δυτικής Μάνης', '', '', 'info@dimosdytikismanis.gr'),
('Δήμος Δυτικής Σάμου', '', '', 'dimosdytikissamou@gmail.com'),
('Δήμος Δωδώνης', '', '', 'info@1239.syzefxis.gov.gr'),
('Δήμος Δωρίδος', '', '', 'lidoriki@otenet.gr'),
('Δήμος Έδεσσας', '', '', 'info@edessa.gr'),
('Δήμος Ελασσόνας', '', '', 'dimoselassonas@hol.gr'),
('Δήμος Ελαφονήσου', '', '', 'dimos@elafonisos.gov.gr'),
('Δήμος Ελευσίνας', '', '', 'vbistiolas@elefsina.gr'),
('Δήμος Ελληνικού-Αργυρούπολης', '', '', 'kortzidis@elliniko.gr'),
('Δήμος Εμμανουήλ Παππά', '', '', 'dimarxosep@0670.syzefxis.gov.gr'),
('Δήμος Εορδαίας', '', '', 'grdhmar@ptolemaida.gr'),
('Δήμος Επιδαύρου', '', '', 'dimasc@otenet.gr'),
('Δήμος Ερέτριας', '', '', 'eretriad@otenet.gr')
ON CONFLICT DO NOTHING;