INSERT INTO municipalities (name_el, name_en, name_de, email_official) VALUES
('Δήμος Πλατανιά', '', '', 'dimos@platanias.gr'),
('Δήμος Πολύγυρου', '', '', 'info@polygyros.gr'),
('Δήμος Πόρου', '', '', 'dimporu1@otenet.gr'),
('Δήμος Πρέβεζας', '', '', 'contact@1485.syzefxis.gov.gr'),
('Δήμος Πρεσπών', '', '', 'prespa@otenet.gr'),
('Δήμος Προσοτσάνης', '', '', 'info@prosotsani.gr'),
('Δήμος Πύδνας-Κολινδρού', '', '', 'aiginio@otenet.gr'),
('Δήμος Πυλαίας-Χορτιάτη', '', '', 'dimarhos.panorama@pilea-hortiatis.gr'),
('Δήμος Πύλης', '', '', 'dpilis@otenet.gr'),
('Δήμος Πύλου - Νέστορος', '', '', 'pylos@otenet.gr'),
('Δήμος Πύργου', '', '', 'dpyrgou@yahoo.gr'),
('Δήμος Πωγωνίου', '', '', 'dkalpaki@otenet.gr'),
('Δήμος Ραφήνας-Πικερμίου', '', '', 'grafeio-dimarxou@0164.syzefxis.gov.gr'),
('Δήμος Ρεθύμνης', '', '', 'dimos@rethymno.gr'),
('Δήμος Ρήγα Φεραίου', '', '', 'd.r.feraiou@0922.syzefgxis.gov.gr'),
('Δήμος Σαλαμίνος', '', '', 'mayor@salamina.gov.gr'),
('Δήμος Σάμης', '', '', 'dimos@sami.gov.gr'),
('Δήμος Σαμοθράκης', '', '', 'dim@samothraki.gr'),
('Δήμος Σερβίων', '', '', 'dservion@otenet.gr'),
('Δήμος Σερίφου', '', '', 'd.serifou@kep.gov.gr'),
('Δήμος Σερρών', '', '', 'mayor@serres.gr'),
('Δήμος Σητείας', '', '', 'info@sitia.gr'),
('Δήμος Σιθωνίας', '', '', 'dimarxos@dimossithonias.gr'),
('Δήμος Σικίνου', '', '', 'dimos@sikinos.gr'),
('Δήμος Σικυωνίων', '', '', 'd-sikyon@otenet.gr'),
('Δήμος Σιντικής', '', '', 'info@sidiki.gr'),
('Δήμος Σίφνου', '', '', 'info@sifnos.gr'),
('Δήμος Σκιάθου', '', '', 'dimos@n-skiathos.gr'),
('Δήμος Σκοπέλου', '', '', 'protok@skopelos.gov.gr'),
('Δήμος Σκύδρας', '', '', 'd_skydras@skydra.gov.gr'),
('Δήμος Σκύρου', '', '', 'dimoskirou@0888.syzefxis.gov.gr'),
('Δήμος Σουλίου', '', '', 'info@paramythia.gr'),
('Δήμος Σουφλίου', '', '', 'dim@0890.syzefxis.gov.gr'),
('Δήμος Σοφάδων', '', '', 'info@sofades.gr'),
('Δήμος Σπάρτης', '', '', 'dimspart@otenet.gr'),
('Δήμος Σπάτων-Αρτέμιδος', '', '', 'dimoss1@otenet.gr'),
('Δήμος Σπετσών', '', '', 'dspetson@hol.gr'),
('Δήμος Στυλίδος', '', '', 'dimarchos-stylidas@stylida.gr'),
('Δήμος Σύμης', '', '', 'dimosymis@yahoo.gr'),
('Δήμος Σύρου - Ερμούπολης', '', '', 'gdekavalas@gmail.com'),
('Δήμος Σφακίων', '', '', 'sfakia-d@otenet.gr'),
('Δήμος Τανάγρας', '', '', 'tanagra@tanagra.gr'),
('Δήμος Τεμπών', '', '', 'makrixor@otenet.gr'),
('Δήμος Τήλου', '', '', 'dimtilos@otenet.gr'),
('Δήμος Τήνου', '', '', 'dtinou@thn.forthnet.gr'),
('Δήμος Τοπείρου', '', '', 'info@topeiros.gr'),
('Δήμος Τρικκαίων', '', '', 'dim_trik@otenet.gr'),
('Δήμος Τρίπολης', '', '', 'dioiktri@otenet.gr'),
('Δήμος Τριφυλίας', '', '', 'dimtrifylias@1391.syzefxis.gov.gr'),
('Δήμος Τροιζηνίας - Μεθάνων', '', '', 'dhmostr@otenet.gr')
ON CONFLICT DO NOTHING;