INSERT INTO municipalities (name_el, name_en, name_de, email_official) VALUES
('Δήμος Κεντρικών Τζουμέρκων', '', '', NULL),
('Δήμος Κερατσινίου - Δραπετσώνας', '', '', 'gram.dim@keratsini.gr'),
('Δήμος Κηφισιάς', '', '', 'dkifisia@otenet.gr'),
('Δήμος Κιλελέρ', '', '', 'dimoskileler@kileler.gov.gr'),
('Δήμος Κιλκίς', '', '', 'info@dhmoskilkis.gr'),
('Δήμος Κιμώλου', '', '', 'k.kimolou@kep.gov.gr'),
('Δήμος Κισσάμου', '', '', 'dkisamou@gmail.com'),
('Δήμος Κοζάνης', '', '', 'dimarkoz@otenet.gr'),
('Δήμος Κομοτηνής', '', '', 'gdkomot@otenet.gr'),
('Δήμος Κόνιτσας', '', '', 'info@konitsa.gr'),
('Δήμος Κορδελιού-Ευόσμου', '', '', 'dimos@kordelio-evosmos.gr'),
('Δήμος Κορινθίων', '', '', 'mail@korinthos.gr'),
('Δήμος Κορυδαλλού', '', '', 'korydallos@korydallos.gr'),
('Δήμος Κρωπίας', '', '', 'koropi@hol.gr'),
('Δήμος Κυθήρων', '', '', 'kythira@otenet.gr'),
('Δήμος Κύθνου', '', '', 'dkithnou@otenet.gr'),
('Δήμος Κύμης-Αλιβερίου', '', '', 'dimos.kimis-aliveriou@0902.syzefxis.gov.gr'),
('Δήμος Κω', '', '', 'kos_mayor@kos.gr'),
('Δήμος Λαγκαδά', '', '', 'lagadas@otenet.gr'),
('Δήμος Λαμιέων', '', '', 'info@lamia-city.gr'),
('Δήμος Λαρισαίων', '', '', 'protokolo@larissa-dimos.gr'),
('Δήμος Λαυρεωτικής', '', '', 'dhmarxos@lavrio.gr'),
('Δήμος Λεβαδέων', '', '', 'gdimarxou@livadia.gr'),
('Δήμος Λειψών', '', '', 'dlipson@otenet.gr'),
('Δήμος Λέρου', '', '', 'dimler66@otenet.gr'),
('Δήμος Λευκάδας', '', '', 'info@dimoslefkadas.gr'),
('Δήμος Λήμνου', '', '', 'dlimnou@gmail.com'),
('Δήμος Ληξουρίου', '', '', 'dimoslixouriou@gmail.com'),
('Δήμος Λίμνης Πλαστήρα', '', '', 'plastiras@hol.gr'),
('Δήμος Λοκρών', '', '', 'ataldim@otenet.gr'),
('Δήμος Λουτρακίου-Περαχώρας-Αγίων Θεοδώρων', '', '', 'info@loutraki.gr'),
('Δήμος Λυκόβρυσης-Πεύκης', '', '', 'likovrisi@likovrisi.gr'),
('Δήμος Μακρακώμης', '', '', 'info@dimosmakrakomis.gov.gr'),
('Δήμος Μαλεβιζίου', '', '', 'malevizi@malevizi.gr'),
('Δήμος Μαντουδίου-Λίμνης-Αγίας Άννας', '', '', 'elimnion@otenet.gr'),
('Δήμος Μαραθώνος', '', '', 'info@marathon.gr'),
('Δήμος Μαρκόπουλου Μεσογαίας', '', '', 'webmaster@markopoulo.gr'),
('Δήμος Μαρωνείας-Σαπών', '', '', 'gd.maroneias-sapon@0873.syzefxis.gov.gr'),
('Δήμος Μεγαλόπολης', '', '', 'info@megalopoli.gr'),
('Δήμος Μεγανησίου', '', '', 'contact@meganisi.gr'),
('Δήμος Μεγαρέων', '', '', 'dhmegara@otenet.gr'),
('Δήμος Μεγίστης', '', '', 'd.megistis@kep.gov.gr'),
('Δήμος Μεσσήνης', '', '', 'messini@otenet.gr'),
('Δήμος Μεταμορφώσεως', '', '', 'webmaster@metamorfossi.gr'),
('Δήμος Μετεώρων', '', '', 'info@dimosmeteoron.com'),
('Δήμος Μετσόβου', '', '', 'dmetsovou@1429.syzefxis.gov.gr'),
('Δήμος Μινώα Πεδιάδας', '', '', 'minoa@minoapediadas.gr'),
('Δήμος Μονεμβασιάς', '', '', 'monemvasia@monemvasia.gr'),
('Δήμος Μοσχάτου-Ταύρου', '', '', 'xypeteon@otenet.gr'),
('Δήμος Μουζακίου', '', '', 'dimos@mouzaki.gr')
ON CONFLICT DO NOTHING;