INSERT INTO municipalities (name_el, name_en, name_de, email_official) VALUES
('Δήμος Μύκης', '', '', 'info@dimosmykis.gr'),
('Δήμος Μυκόνου', '', '', 'dmykonou@otenet.gr'),
('Δήμος Μυλοποτάμου', '', '', 'Perama1@otenet.gr'),
('Δήμος Μυτιλήνης', '', '', 'grafeiotypou@mytilene.gr'),
('Δήμος Νάξου και Μικρών Κυκλάδων', '', '', 'naxos@1442.syzefxis.gov.gr'),
('Δήμος Ναυπακτίας', '', '', 'info@nafpaktos.gr'),
('Δήμος Ναυπλιέων', '', '', 'nafpldim@otenet.gr'),
('Δήμος Νεάπολης-Συκεών', '', '', 'neapoli.sykies@dtt.gov.gr'),
('Δήμος Νέας Ζίχνης', '', '', 'n-zixni@otenet.gr'),
('Δήμος Νέας Ιωνίας', '', '', 'protocol@neaionia.gr'),
('Δήμος Νέας Προποντίδας', '', '', 'mayor@nea-propontida.gr'),
('Δήμος Νέας Σμύρνης', '', '', 'dnsmyrni@hellasnet.gr'),
('Δήμος Νέας Φιλαδέλφειας - Νέας Χαλκηδόνος', '', '', 'neafiladelfeia@neafiladelfeia.gr'),
('Δήμος Νεμέας', '', '', 'nemeaota@otenet.gr'),
('Δήμος Νεστορίου', '', '', 'nestokep@otenet.gr'),
('Δήμος Νέστου', '', '', 'dhmoxrys@otenet.gr'),
('Δήμος Νικολάου Σκουφά', '', '', 'dimos@nskoufas.gr'),
('Δήμος Νισύρου', '', '', 'nisyros2@otenet.gr'),
('Δήμος Νότιας Κέρκυρας', '', '', 'info@1406.syzefxis.gov.gr'),
('Δήμος Νότιας Κυνουρίας', '', '', 'info@notiakynouria.gov.gr'),
('Δήμος Νοτίου Πηλίου', '', '', 'dimos.notiou.piliou@gmail.com'),
('Δήμος Ξάνθης', '', '', 'protocol@cityofxanthi.gr'),
('Δήμος Ξηρομέρου', '', '', 'dastakou@otenet.gr'),
('Δήμος Ξυλοκάστρου-Ευρωστίνης', '', '', 'info@xylokastro.gov.gr'),
('Δήμος Οινουσσών', '', '', 'oinouses@0814.syzefxis.gov.gr'),
('Δήμος Οιχαλίας', '', '', 'meligala@otenet.gr'),
('Δήμος Ορεστιάδας', '', '', 'mayor@orestiada.gr'),
('Δήμος Οροπεδίου Λασιθίου', '', '', 'info@oropediadolas.gr'),
('Δήμος Ορχομενού', '', '', 'info@orchomenos.gr'),
('Δήμος Παγγαίου', '', '', 'info@dimospaggaiou.gr'),
('Δήμος Παιανίας', '', '', 'paiania_mayor@paiania.gr'),
('Δήμος Παιονίας', '', '', 'info@municipalityofpaionia.gr'),
('Δήμος Παλαιού Φαλήρου', '', '', 'secretary.dpf@palaiofaliro.gr'),
('Δήμος Παλαμά', '', '', 'info@palamascity.gr'),
('Δήμος Παλλήνης', '', '', 'info@gerakas.gr'),
('Δήμος Παξών', '', '', 'info@paxi.gr'),
('Δήμος Παπάγου-Χολαργού', '', '', 'dimarxos@holargos.gr'),
('Δήμος Παρανεστίου', '', '', 'paranest@otenet.gr'),
('Δήμος Πάργας', '', '', 'info@dimospargas.gr'),
('Δήμος Πάρου', '', '', 'info@paros.gr'),
('Δήμος Πάτμου', '', '', 'info@patmos.gov.gr'),
('Δήμος Πατρέων', '', '', 'mayor@patras.gr'),
('Δήμος Παύλου Μελά', '', '', 'dpm@pavlosmelas.gr'),
('Δήμος Πειραιώς', '', '', 'mayor@pireasnet.gr'),
('Δήμος Πέλλας', '', '', 'dimos@giannitsa.gr'),
('Δήμος Πεντέλης', '', '', 'info@penteli.gov.gr'),
('Δήμος Περάματος', '', '', 'grdimper@otenet.gr'),
('Δήμος Περιστερίου', '', '', 'mayor@peristeri.gr'),
('Δήμος Πετρουπόλεως', '', '', 'petroupoli@petroupoli.gov.gr'),
('Δήμος Πηνειού', '', '', 'dimospineiou@1312.syzefxis.gov.gr')
ON CONFLICT DO NOTHING;