INSERT INTO municipalities (name_el, name_en, name_de, email_official) VALUES
('Δήμος Ερμιονίδας', '', '', 'm.ermionidas@gmail.com'),
('Δήμος Ερυμάνθου', '', '', 'difarron@otenet.gr'),
('Δήμος Ευρώτα', '', '', 'info@eurota.gr'),
('Δήμος Ζαγοράς-Μουρεσίου', '', '', 'd.zagoras@kep.gov.gr'),
('Δήμος Ζαγορίου', '', '', 'd.zagoriou@1376.syzefxis.gov.gr'),
('Δήμος Ζακύνθου', '', '', 'info@1280.syzefxis.gov.gr'),
('Δήμος Ζαχάρως', '', '', 'dzaxaro1@otenet.gr'),
('Δήμος Ζηρού', '', '', 'info@dimoszirou.gr'),
('Δήμος Ζίτσας', '', '', 'zitsa@zitsa.gov.gr'),
('Δήμος Ζωγράφου', '', '', 'dhmarxos@zografou.gr'),
('Δήμος Ηγουμενίτσας', '', '', 'info@igoumenitsa.gr'),
('Δήμος Ήλιδας', '', '', 'info@amaliada.gr'),
('Δήμος Ηλιουπόλεως', '', '', 'info@ilioupoli.gr'),
('Δήμος Ηρακλείας', '', '', 'info@dimosiraklias.gr'),
('Δήμος Ηρακλείου Κρήτης', '', '', 'info@heraklion.gr'),
('Δήμος Ηρακλείου Αττικής', '', '', 'dimiraklio@iraklio.gr'),
('Δήμος Ηρωικής Νήσου Κάσου', '', '', 'dimkasos@otenet.gr'),
('Δήμος Ηρωικής Νήσου Ψαρών', '', '', 'psara2@otenet.gr'),
('Δήμος Ηρωικής Πόλεως Νάουσας', '', '', 'info@naoussa.gr'),
('Δήμος Θάσου', '', '', 'dimos@thassos.gr'),
('Δήμος Θερμαϊκού', '', '', 'press@thermaikos.gr'),
('Δήμος Θέρμου', '', '', 'dthermo@otenet.gr'),
('Δήμος Θεσσαλονίκης', '', '', 'mayor@thessaloniki.gr'),
('Δήμος Θηβαίων', '', '', 'dimosthivas@thiva.gr'),
('Δήμος Ιάσμου', '', '', 'politis@iasmos.gr'),
('Δήμος Ιεράπετρας', '', '', 'dimos@ierapetra.gov.gr'),
('Δήμος Ιεράς Πόλης Μεσολογγίου', '', '', 'syzefxis@1426.syzefxis.gov.gr'),
('Δήμος Ιητών', '', '', 'info@dimosios.gr'),
('Δήμος Ιθάκης', '', '', 'd_Ithakii@otenet.gr'),
('Δήμος Ικαρίας', '', '', 'dak2@otenet.gr'),
('Δήμος Ιλίου', '', '', 'ilion@ilion.gr'),
('Δήμος Ιστιαίας - Αιδηψού', '', '', 'info@dimosistiaiasaidipsou.gr'),
('Δήμος Ιωαννιτών', '', '', 'mayor@ioannina.gr'),
('Δήμος Καβάλας', '', '', 'mayor@kavala.gov.gr'),
('Δήμος Καισαριανής', '', '', 'dimos@kessariani.gr'),
('Δήμος Καλαβρύτων', '', '', 'dimos.kalavriton@1363.syzefxis.gov.gr'),
('Δήμος Καλαμάτας', '', '', 'info@kalamata.gr'),
('Δήμος Καλλιθέας', '', '', 'dimarxos@kallithea.gr'),
('Δήμος Καλυμνίων', '', '', 'mok@kalymnos.gr'),
('Δήμος Καμένων Βούρλων', '', '', 'info@mwlos.gr'),
('Δήμος Καντάνου - Σελίνου', '', '', 'info@kantanouselinou.gr'),
('Δήμος Καρδίτσας', '', '', 'municipality@dimoskarditsas.gov.gr'),
('Δήμος Καρπενησίου', '', '', 'contact@karpenissi.gr'),
('Δήμος Καρύστου', '', '', 'dkaristos@hol.gr'),
('Δήμος Κασσάνδρας', '', '', 'otakas1@otenet.gr'),
('Δήμος Καστοριάς', '', '', 'dkast1@otenet.gr'),
('Δήμος Κατερίνης', '', '', 'katerini@hol.gr'),
('Δήμος Κάτω Νευροκοπίου', '', '', 'dhmneur@otenet.gr'),
('Δήμος Κέας', '', '', 'kea@kea.gr'),
('Δήμος Κεντρικής Κέρκυρας και Διαποντίων Νήσων', '', '', 'info@corfu.gov.gr')
ON CONFLICT DO NOTHING;