-- 319 rows to insert
INSERT INTO municipalities (name_el, name_en, name_de, email_official) VALUES
('Δήμος Αβδήρων', '', '', 'info@avdera.gr'),
('Δήμος Αγαθονησίου', '', '', 'k.agathonisiou@kep.gov.gr'),
('Δήμος Αγιάς', '', '', 'mayordagias@0559.syzefxis.gov.gr'),
('Δήμος Αγίας Βαρβάρας', '', '', 'grdim@agiavarvara.gr'),
('Δήμος Αγίας Παρασκευής', '', '', 'dimos@agiaparaskevi.gr'),
('Δήμος Αγίου Βασιλείου', '', '', 'dimoslam@otenet.gr'),
('Δήμος Αγίου Δημητρίου', '', '', 'dad-may@dad.gr'),
('Δήμος Αγίου Ευστρατίου', '', '', 'aistratis@altecnet.gr'),
('Δήμος Αγίου Νικολάου', '', '', 'grafdim@yahoo.gr'),
('Δήμος Αγίων Αναργύρων - Καματερού', '', '', 'agiianargirinas@0087.syzefxis.gov.gr'),
('Δήμος Αγκιστρίου', '', '', 'kagistri@otenet.gr'),
('Δήμος Αγράφων', '', '', 'info@agrafa.gr'),
('Δήμος Αγρινίου', '', '', 'dimarxos@agrinio.gr'),
('Δήμος Αθηναίων', '', '', 'mayor@athens.gr'),
('Δήμος Αιγάλεω', '', '', 'egaleo@egaleo.gr'),
('Δήμος Αιγιαλείας', '', '', 'admin@aigialeia.gov.gr'),
('Δήμος Αίγινας', '', '', 'grafeiodimarxou@aeginadimos.gr'),
('Δήμος Ακτίου-Βόνιτσας', '', '', 'anact@otenet.gr'),
('Δήμος Αλεξάνδρειας', '', '', 'info@alexandria.gr'),
('Δήμος Αλεξανδρούπολης', '', '', 'dimarxos@alexpolis.gr'),
('Δήμος Αλιάρτου - Θεσπιέων', '', '', 'aliartos@otenet.gr'),
('Δήμος Αλίμου', '', '', 'info@alimos.gr'),
('Δήμος Αλμυρού', '', '', 'gram.dhmarxou@almiros.gr'),
('Δήμος Αλμωπίας', '', '', 'syzefxis@0598.syzefxis.gov.gr'),
('Δήμος Αλοννήσου', '', '', 'dimosalo@otenet.gr'),
('Δήμος Αμαρίου', '', '', 'info@amario.com.gr'),
('Δήμος Αμαρουσίου', '', '', 'dimarxos@maroussi.gr'),
('Δήμος Αμοργού', '', '', 'amorgos@aigaio.gr'),
('Δήμος Αμπελοκήπων-Μενεμένης', '', '', 'info@ampelokipi-menemeni.gr'),
('Δήμος Αμυνταίου', '', '', 'dimarxos@amyntaio.gr'),
('Δήμος Αμφίκλειας-Ελάτειας', '', '', 'info@dimos-amfiklias-elatias.gr'),
('Δήμος Αμφιλοχίας', '', '', 'dimamfil@otenet.gr'),
('Δήμος Αμφίπολης', '', '', 'info@dimos-amfipolis.gr'),
('Δήμος Ανατολικής Μάνης', '', '', 'dimarxos@1315.syzefxis.gov.gr'),
('Δήμος Ανατολικής Σάμου', '', '', 'news@vathi.gr'),
('Δήμος Ανάφης', '', '', 'k-anafis@otenet.gr'),
('Δήμος Ανδραβίδας - Κυλλήνης', '', '', 'dlehena@yahoo.gr'),
('Δήμος Ανδρίτσαινας - Κρεστένων', '', '', 'dkresten@otenet.gr'),
('Δήμος Άνδρου', '', '', 'dimos@andros.gr'),
('Δήμος Αντιπάρου', '', '', 'k.antiparou@kep.gov.gr'),
('Δήμος Ανωγείων', '', '', 'info@anogeia.gr'),
('Δήμος Αποκορώνου', '', '', 'info@apokoronas.gov.gr'),
('Δήμος Αργιθέας', '', '', 'd.argitheas@kep.gov.gr'),
('Δήμος Αργοστολίου', '', '', 'dimarxos_arg@kefallonia.gov.gr'),
('Δήμος Άργους - Μυκηνών', '', '', 'dimos@argos.gr'),
('Δήμος Άργους Ορεστικού', '', '', 'info@argosorestiko.gr'),
('Δήμος Αριστοτέλη', '', '', 'dhmstaka@otenet.gr'),
('Δήμος Αρριανών', '', '', 'filyra@0924.syzefxis.gov.gr'),
('Δήμος Αρταίων', '', '', 'dimos@arta.gr'),
('Δήμος Αρχαίας Ολυμπίας', '', '', 'dolympia@otenet.gr')
ON CONFLICT DO NOTHING;

INSERT INTO municipalities (name_el, name_en, name_de, email_official) VALUES
('Δήμος Αρχανών - Αστερουσίων', '', '', 'info@0470.syzefxis.gov.gr'),
('Δήμος Ασπροπύργου', '', '', 'grafeiodimarxou@aspropyrgos.gr'),
('Δήμος Αστυπάλαιας', '', '', 'astypalaia@astypalaia.gr'),
('Δήμος Αχαρνών', '', '', 'grdhm1@acharnes.gr'),
('Δήμος Βάρης - Βούλας - Βουλιαγμένης', '', '', 'info@vvv.gov.gr'),
('Δήμος Βελβεντού', '', '', 'grammatia@velvento.gr'),
('Δήμος Βέλου-Βόχας', '', '', 'masouri@vochas.gov.gr'),
('Δήμος Βέροιας', '', '', 'dimosverias@veria.gr'),
('Δήμος Βιάννου', '', '', 'dviannos@otenet.gr'),
('Δήμος Βισαλτίας', '', '', 'dnigr622@otenet.gr'),
('Δήμος Βοΐου', '', '', 'dimos_siatista@yahoo.gr'),
('Δήμος Βόλβης', '', '', 'dimos@dimosvolvis.gr'),
('Δήμος Βόρειας Κέρκυρας', '', '', 'info@1354.syzefxis.gov.gr'),
('Δήμος Βορείων Τζουμέρκων', '', '', 'info@voreiatzoumerka.gr'),
('Δήμος Βριλησσίων', '', '', 'noni@vrilissia.gr'),
('Δήμος Βύρωνος', '', '', 'dimarxos@dimosbyrona.gr'),
('Δήμος Γαλατσίου', '', '', 'info@galatsi.gr'),
('Δήμος Γαύδου', '', '', 'dimos@gavdos.gr'),
('Δήμος Γεωργίου Καραϊσκάκη', '', '', 'dgk1@otenet.gr'),
('Δήμος Γλυφάδας', '', '', 'grammateia@0114.syzefxis.gov.gr'),
('Δήμος Γόρτυνας', '', '', 'gortyna@in.gr'),
('Δήμος Γορτυνίας', '', '', 'ddimitsa@otenet.gr'),
('Δήμος Γρεβενών', '', '', 'dimosgrevenon@0641.syzefxis.gov.gr'),
('Δήμος Δάφνης - Υμηττού', '', '', 'dafni05@otenet.gr'),
('Δήμος Δέλτα', '', '', 'grammateia@dimosdelta.gr'),
('Δήμος Δελφών', '', '', 'dimarxos@delphi.gov.gr'),
('Δήμος Δεσκάτης', '', '', 'dimosdes@otenet.gr'),
('Δήμος Διδυμοτείχου', '', '', 'mayor@didymoteicho.gr'),
('Δήμος Διονύσου', '', '', 'secretary@agstefanos.gr'),
('Δήμος Δίου-Ολύμπου', '', '', 'dimos@dion-olympos.gr'),
('Δήμος Διρφύων-Μεσσαπίων', '', '', 'messapia@otenet.gr'),
('Δήμος Διστόμου-Αράχοβας-Αντίκυρας', '', '', 'info@daa.gov.gr'),
('Δήμος Δομοκού', '', '', 'info@domokos.gr'),
('Δήμος Δοξάτου', '', '', 'dimarxos@doxato.gr'),
('Δήμος Δράμας', '', '', 'dhmos-dramas@dra.forthnet.gr'),
('Δήμος Δυτικής Αχαΐας', '', '', 'mayor@dimosdymaion.gov.gr'),
('Δήμος Δυτικής Λέσβου', '', '', 'grafeiodimarxou@mwlesvos.gr'),
('Δήμος Δυτικής Μάνης', '', '', 'info@dimosdytikismanis.gr'),
('Δήμος Δυτικής Σάμου', '', '', 'dimosdytikissamou@gmail.com'),
('Δήμος Δωδώνης', '', '', 'info@1239.syzefxis.gov.gr'),
('Δήμος Δωρίδος', '', '', 'lidoriki@otenet.gr'),
('Δήμος Έδεσσας', '', '', 'info@edessa.gr'),
('Δήμος Ελασσόνας', '', '', 'dimoselassonas@hol.gr'),
('Δήμος Ελαφονήσου', '', '', 'dimos@elafonisos.gov.gr'),
('Δήμος Ελευσίνας', '', '', 'vbistiolas@elefsina.gr'),
('Δήμος Ελληνικού-Αργυρούπολης', '', '', 'kortzidis@elliniko.gr'),
('Δήμος Εμμανουήλ Παππά', '', '', 'dimarxosep@0670.syzefxis.gov.gr'),
('Δήμος Εορδαίας', '', '', 'grdhmar@ptolemaida.gr'),
('Δήμος Επιδαύρου', '', '', 'dimasc@otenet.gr'),
('Δήμος Ερέτριας', '', '', 'eretriad@otenet.gr')
ON CONFLICT DO NOTHING;

INSERT INTO municipalities (name_el, name_en, name_de, email_official) VALUES
('Δήμος Ερμιονίδας', '', '', 'm.ermionidas@gmail.com'),
('Δήμος Ερυμάνθου', '', '', 'difarron@otenet.gr'),
('Δήμος Ευρώτα', '', '', 'info@eurota.gr'),
('Δήμος Ζαγοράς-Μουρεσίου', '', '', 'd.zagoras@kep.gov.gr'),
('Δήμος Ζαγορίου', '', '', 'd.zagoriou@1376.syzefxis.gov.gr'),
('Δήμος Ζακύνθου', '', '', 'info@1280.syzefxis.gov.gr'),
('Δήμος Ζαχάρως', '', '', 'dzaxaro1@otenet.gr'),
('Δήμος Ζηρού', '', '', 'info@dimoszirou.gr'),
('Δήμος Ζίτσας', '', '', 'zitsa@zitsa.gov.gr'),
('Δήμος Ζωγράφου', '', '', 'dhmarxos@zografou.gr'),
('Δήμος Ηγουμενίτσας', '', '', 'info@igoumenitsa.gr'),
('Δήμος Ήλιδας', '', '', 'info@amaliada.gr'),
('Δήμος Ηλιουπόλεως', '', '', 'info@ilioupoli.gr'),
('Δήμος Ηρακλείας', '', '', 'info@dimosiraklias.gr'),
('Δήμος Ηρακλείου Κρήτης', '', '', 'info@heraklion.gr'),
('Δήμος Ηρακλείου Αττικής', '', '', 'dimiraklio@iraklio.gr'),
('Δήμος Ηρωικής Νήσου Κάσου', '', '', 'dimkasos@otenet.gr'),
('Δήμος Ηρωικής Νήσου Ψαρών', '', '', 'psara2@otenet.gr'),
('Δήμος Ηρωικής Πόλεως Νάουσας', '', '', 'info@naoussa.gr'),
('Δήμος Θάσου', '', '', 'dimos@thassos.gr'),
('Δήμος Θερμαϊκού', '', '', 'press@thermaikos.gr'),
('Δήμος Θέρμου', '', '', 'dthermo@otenet.gr'),
('Δήμος Θεσσαλονίκης', '', '', 'mayor@thessaloniki.gr'),
('Δήμος Θηβαίων', '', '', 'dimosthivas@thiva.gr'),
('Δήμος Ιάσμου', '', '', 'politis@iasmos.gr'),
('Δήμος Ιεράπετρας', '', '', 'dimos@ierapetra.gov.gr'),
('Δήμος Ιεράς Πόλης Μεσολογγίου', '', '', 'syzefxis@1426.syzefxis.gov.gr'),
('Δήμος Ιητών', '', '', 'info@dimosios.gr'),
('Δήμος Ιθάκης', '', '', 'd_Ithakii@otenet.gr'),
('Δήμος Ικαρίας', '', '', 'dak2@otenet.gr'),
('Δήμος Ιλίου', '', '', 'ilion@ilion.gr'),
('Δήμος Ιστιαίας - Αιδηψού', '', '', 'info@dimosistiaiasaidipsou.gr'),
('Δήμος Ιωαννιτών', '', '', 'mayor@ioannina.gr'),
('Δήμος Καβάλας', '', '', 'mayor@kavala.gov.gr'),
('Δήμος Καισαριανής', '', '', 'dimos@kessariani.gr'),
('Δήμος Καλαβρύτων', '', '', 'dimos.kalavriton@1363.syzefxis.gov.gr'),
('Δήμος Καλαμάτας', '', '', 'info@kalamata.gr'),
('Δήμος Καλλιθέας', '', '', 'dimarxos@kallithea.gr'),
('Δήμος Καλυμνίων', '', '', 'mok@kalymnos.gr'),
('Δήμος Καμένων Βούρλων', '', '', 'info@mwlos.gr'),
('Δήμος Καντάνου - Σελίνου', '', '', 'info@kantanouselinou.gr'),
('Δήμος Καρδίτσας', '', '', 'municipality@dimoskarditsas.gov.gr'),
('Δήμος Καρπενησίου', '', '', 'contact@karpenissi.gr'),
('Δήμος Καρύστου', '', '', 'dkaristos@hol.gr'),
('Δήμος Κασσάνδρας', '', '', 'otakas1@otenet.gr'),
('Δήμος Καστοριάς', '', '', 'dkast1@otenet.gr'),
('Δήμος Κατερίνης', '', '', 'katerini@hol.gr'),
('Δήμος Κάτω Νευροκοπίου', '', '', 'dhmneur@otenet.gr'),
('Δήμος Κέας', '', '', 'kea@kea.gr'),
('Δήμος Κεντρικής Κέρκυρας και Διαποντίων Νήσων', '', '', 'info@corfu.gov.gr')
ON CONFLICT DO NOTHING;

INSERT INTO municipalities (name_el, name_en, name_de, email_official) VALUES
('Δήμος Κεντρικών Τζουμέρκων', '', '', NULL),
('Δήμος Κερατσινίου - Δραπετσώνας', '', '', 'gram.dim@keratsini.gr'),
('Δήμος Κηφισιάς', '', '', 'dkifisia@otenet.gr'),
('Δήμος Κιλελέρ', '', '', 'dimoskileler@kileler.gov.gr'),
('Δήμος Κιλκίς', '', '', 'info@dhmoskilkis.gr'),
('Δήμος Κιμώλου', '', '', 'k.kimolou@kep.gov.gr'),
('Δήμος Κισσάμου', '', '', 'dkisamou@gmail.com'),
('Δήμος Κοζάνης', '', '', 'dimarkoz@otenet.gr'),
('Δήμος Κομοτηνής', '', '', 'gdkomot@otenet.gr'),
('Δήμος Κόνιτσας', '', '', 'info@konitsa.gr'),
('Δήμος Κορδελιού-Ευόσμου', '', '', 'dimos@kordelio-evosmos.gr'),
('Δήμος Κορινθίων', '', '', 'mail@korinthos.gr'),
('Δήμος Κορυδαλλού', '', '', 'korydallos@korydallos.gr'),
('Δήμος Κρωπίας', '', '', 'koropi@hol.gr'),
('Δήμος Κυθήρων', '', '', 'kythira@otenet.gr'),
('Δήμος Κύθνου', '', '', 'dkithnou@otenet.gr'),
('Δήμος Κύμης-Αλιβερίου', '', '', 'dimos.kimis-aliveriou@0902.syzefxis.gov.gr'),
('Δήμος Κω', '', '', 'kos_mayor@kos.gr'),
('Δήμος Λαγκαδά', '', '', 'lagadas@otenet.gr'),
('Δήμος Λαμιέων', '', '', 'info@lamia-city.gr'),
('Δήμος Λαρισαίων', '', '', 'protokolo@larissa-dimos.gr'),
('Δήμος Λαυρεωτικής', '', '', 'dhmarxos@lavrio.gr'),
('Δήμος Λεβαδέων', '', '', 'gdimarxou@livadia.gr'),
('Δήμος Λειψών', '', '', 'dlipson@otenet.gr'),
('Δήμος Λέρου', '', '', 'dimler66@otenet.gr'),
('Δήμος Λευκάδας', '', '', 'info@dimoslefkadas.gr'),
('Δήμος Λήμνου', '', '', 'dlimnou@gmail.com'),
('Δήμος Ληξουρίου', '', '', 'dimoslixouriou@gmail.com'),
('Δήμος Λίμνης Πλαστήρα', '', '', 'plastiras@hol.gr'),
('Δήμος Λοκρών', '', '', 'ataldim@otenet.gr'),
('Δήμος Λουτρακίου-Περαχώρας-Αγίων Θεοδώρων', '', '', 'info@loutraki.gr'),
('Δήμος Λυκόβρυσης-Πεύκης', '', '', 'likovrisi@likovrisi.gr'),
('Δήμος Μακρακώμης', '', '', 'info@dimosmakrakomis.gov.gr'),
('Δήμος Μαλεβιζίου', '', '', 'malevizi@malevizi.gr'),
('Δήμος Μαντουδίου-Λίμνης-Αγίας Άννας', '', '', 'elimnion@otenet.gr'),
('Δήμος Μαραθώνος', '', '', 'info@marathon.gr'),
('Δήμος Μαρκόπουλου Μεσογαίας', '', '', 'webmaster@markopoulo.gr'),
('Δήμος Μαρωνείας-Σαπών', '', '', 'gd.maroneias-sapon@0873.syzefxis.gov.gr'),
('Δήμος Μεγαλόπολης', '', '', 'info@megalopoli.gr'),
('Δήμος Μεγανησίου', '', '', 'contact@meganisi.gr'),
('Δήμος Μεγαρέων', '', '', 'dhmegara@otenet.gr'),
('Δήμος Μεγίστης', '', '', 'd.megistis@kep.gov.gr'),
('Δήμος Μεσσήνης', '', '', 'messini@otenet.gr'),
('Δήμος Μεταμορφώσεως', '', '', 'webmaster@metamorfossi.gr'),
('Δήμος Μετεώρων', '', '', 'info@dimosmeteoron.com'),
('Δήμος Μετσόβου', '', '', 'dmetsovou@1429.syzefxis.gov.gr'),
('Δήμος Μινώα Πεδιάδας', '', '', 'minoa@minoapediadas.gr'),
('Δήμος Μονεμβασιάς', '', '', 'monemvasia@monemvasia.gr'),
('Δήμος Μοσχάτου-Ταύρου', '', '', 'xypeteon@otenet.gr'),
('Δήμος Μουζακίου', '', '', 'dimos@mouzaki.gr')
ON CONFLICT DO NOTHING;

INSERT INTO municipalities (name_el, name_en, name_de, email_official) VALUES
('Δήμος Μύκης', '', '', 'info@dimosmykis.gr'),
('Δήμος Μυκόνου', '', '', 'dmykonou@otenet.gr'),
('Δήμος Μυλοποτάμου', '', '', 'Perama1@otenet.gr'),
('Δήμος Μυτιλήνης', '', '', 'grafeiotypou@mytilene.gr'),
('Δήμος Νάξου και Μικρών Κυκλάδων', '', '', 'naxos@1442.syzefxis.gov.gr'),
('Δήμος Ναυπακτίας', '', '', 'info@nafpaktos.gr'),
('Δήμος Ναυπλιέων', '', '', 'nafpldim@otenet.gr'),
('Δήμος Νεάπολης-Συκεών', '', '', 'neapoli.sykies@dtt.gov.gr'),
('Δήμος Νέας Ζίχνης', '', '', 'n-zixni@otenet.gr'),
('Δήμος Νέας Ιωνίας', '', '', 'protocol@neaionia.gr'),
('Δήμος Νέας Προποντίδας', '', '', 'mayor@nea-propontida.gr'),
('Δήμος Νέας Σμύρνης', '', '', 'dnsmyrni@hellasnet.gr'),
('Δήμος Νέας Φιλαδέλφειας - Νέας Χαλκηδόνος', '', '', 'neafiladelfeia@neafiladelfeia.gr'),
('Δήμος Νεμέας', '', '', 'nemeaota@otenet.gr'),
('Δήμος Νεστορίου', '', '', 'nestokep@otenet.gr'),
('Δήμος Νέστου', '', '', 'dhmoxrys@otenet.gr'),
('Δήμος Νικολάου Σκουφά', '', '', 'dimos@nskoufas.gr'),
('Δήμος Νισύρου', '', '', 'nisyros2@otenet.gr'),
('Δήμος Νότιας Κέρκυρας', '', '', 'info@1406.syzefxis.gov.gr'),
('Δήμος Νότιας Κυνουρίας', '', '', 'info@notiakynouria.gov.gr'),
('Δήμος Νοτίου Πηλίου', '', '', 'dimos.notiou.piliou@gmail.com'),
('Δήμος Ξάνθης', '', '', 'protocol@cityofxanthi.gr'),
('Δήμος Ξηρομέρου', '', '', 'dastakou@otenet.gr'),
('Δήμος Ξυλοκάστρου-Ευρωστίνης', '', '', 'info@xylokastro.gov.gr'),
('Δήμος Οινουσσών', '', '', 'oinouses@0814.syzefxis.gov.gr'),
('Δήμος Οιχαλίας', '', '', 'meligala@otenet.gr'),
('Δήμος Ορεστιάδας', '', '', 'mayor@orestiada.gr'),
('Δήμος Οροπεδίου Λασιθίου', '', '', 'info@oropediadolas.gr'),
('Δήμος Ορχομενού', '', '', 'info@orchomenos.gr'),
('Δήμος Παγγαίου', '', '', 'info@dimospaggaiou.gr'),
('Δήμος Παιανίας', '', '', 'paiania_mayor@paiania.gr'),
('Δήμος Παιονίας', '', '', 'info@municipalityofpaionia.gr'),
('Δήμος Παλαιού Φαλήρου', '', '', 'secretary.dpf@palaiofaliro.gr'),
('Δήμος Παλαμά', '', '', 'info@palamascity.gr'),
('Δήμος Παλλήνης', '', '', 'info@gerakas.gr'),
('Δήμος Παξών', '', '', 'info@paxi.gr'),
('Δήμος Παπάγου-Χολαργού', '', '', 'dimarxos@holargos.gr'),
('Δήμος Παρανεστίου', '', '', 'paranest@otenet.gr'),
('Δήμος Πάργας', '', '', 'info@dimospargas.gr'),
('Δήμος Πάρου', '', '', 'info@paros.gr'),
('Δήμος Πάτμου', '', '', 'info@patmos.gov.gr'),
('Δήμος Πατρέων', '', '', 'mayor@patras.gr'),
('Δήμος Παύλου Μελά', '', '', 'dpm@pavlosmelas.gr'),
('Δήμος Πειραιώς', '', '', 'mayor@pireasnet.gr'),
('Δήμος Πέλλας', '', '', 'dimos@giannitsa.gr'),
('Δήμος Πεντέλης', '', '', 'info@penteli.gov.gr'),
('Δήμος Περάματος', '', '', 'grdimper@otenet.gr'),
('Δήμος Περιστερίου', '', '', 'mayor@peristeri.gr'),
('Δήμος Πετρουπόλεως', '', '', 'petroupoli@petroupoli.gov.gr'),
('Δήμος Πηνειού', '', '', 'dimospineiou@1312.syzefxis.gov.gr')
ON CONFLICT DO NOTHING;

INSERT INTO municipalities (name_el, name_en, name_de, email_official) VALUES
('Δήμος Πλατανιά', '', '', 'dimos@platanias.gr'),
('Δήμος Πολύγυρου', '', '', 'info@polygyros.gr'),
('Δήμος Πόρου', '', '', 'dimporu1@otenet.gr'),
('Δήμος Πρέβεζας', '', '', 'contact@1485.syzefxis.gov.gr'),
('Δήμος Πρεσπών', '', '', 'prespa@otenet.gr'),
('Δήμος Προσοτσάνης', '', '', 'info@prosotsani.gr'),
('Δήμος Πύδνας-Κολινδρού', '', '', 'aiginio@otenet.gr'),
('Δήμος Πυλαίας-Χορτιάτη', '', '', 'dimarhos.panorama@pilea-hortiatis.gr'),
('Δήμος Πύλης', '', '', 'dpilis@otenet.gr'),
('Δήμος Πύλου - Νέστορος', '', '', 'pylos@otenet.gr'),
('Δήμος Πύργου', '', '', 'dpyrgou@yahoo.gr'),
('Δήμος Πωγωνίου', '', '', 'dkalpaki@otenet.gr'),
('Δήμος Ραφήνας-Πικερμίου', '', '', 'grafeio-dimarxou@0164.syzefxis.gov.gr'),
('Δήμος Ρεθύμνης', '', '', 'dimos@rethymno.gr'),
('Δήμος Ρήγα Φεραίου', '', '', 'd.r.feraiou@0922.syzefgxis.gov.gr'),
('Δήμος Σαλαμίνος', '', '', 'mayor@salamina.gov.gr'),
('Δήμος Σάμης', '', '', 'dimos@sami.gov.gr'),
('Δήμος Σαμοθράκης', '', '', 'dim@samothraki.gr'),
('Δήμος Σερβίων', '', '', 'dservion@otenet.gr'),
('Δήμος Σερίφου', '', '', 'd.serifou@kep.gov.gr'),
('Δήμος Σερρών', '', '', 'mayor@serres.gr'),
('Δήμος Σητείας', '', '', 'info@sitia.gr'),
('Δήμος Σιθωνίας', '', '', 'dimarxos@dimossithonias.gr'),
('Δήμος Σικίνου', '', '', 'dimos@sikinos.gr'),
('Δήμος Σικυωνίων', '', '', 'd-sikyon@otenet.gr'),
('Δήμος Σιντικής', '', '', 'info@sidiki.gr'),
('Δήμος Σίφνου', '', '', 'info@sifnos.gr'),
('Δήμος Σκιάθου', '', '', 'dimos@n-skiathos.gr'),
('Δήμος Σκοπέλου', '', '', 'protok@skopelos.gov.gr'),
('Δήμος Σκύδρας', '', '', 'd_skydras@skydra.gov.gr'),
('Δήμος Σκύρου', '', '', 'dimoskirou@0888.syzefxis.gov.gr'),
('Δήμος Σουλίου', '', '', 'info@paramythia.gr'),
('Δήμος Σουφλίου', '', '', 'dim@0890.syzefxis.gov.gr'),
('Δήμος Σοφάδων', '', '', 'info@sofades.gr'),
('Δήμος Σπάρτης', '', '', 'dimspart@otenet.gr'),
('Δήμος Σπάτων-Αρτέμιδος', '', '', 'dimoss1@otenet.gr'),
('Δήμος Σπετσών', '', '', 'dspetson@hol.gr'),
('Δήμος Στυλίδος', '', '', 'dimarchos-stylidas@stylida.gr'),
('Δήμος Σύμης', '', '', 'dimosymis@yahoo.gr'),
('Δήμος Σύρου - Ερμούπολης', '', '', 'gdekavalas@gmail.com'),
('Δήμος Σφακίων', '', '', 'sfakia-d@otenet.gr'),
('Δήμος Τανάγρας', '', '', 'tanagra@tanagra.gr'),
('Δήμος Τεμπών', '', '', 'makrixor@otenet.gr'),
('Δήμος Τήλου', '', '', 'dimtilos@otenet.gr'),
('Δήμος Τήνου', '', '', 'dtinou@thn.forthnet.gr'),
('Δήμος Τοπείρου', '', '', 'info@topeiros.gr'),
('Δήμος Τρικκαίων', '', '', 'dim_trik@otenet.gr'),
('Δήμος Τρίπολης', '', '', 'dioiktri@otenet.gr'),
('Δήμος Τριφυλίας', '', '', 'dimtrifylias@1391.syzefxis.gov.gr'),
('Δήμος Τροιζηνίας - Μεθάνων', '', '', 'dhmostr@otenet.gr')
ON CONFLICT DO NOTHING;

INSERT INTO municipalities (name_el, name_en, name_de, email_official) VALUES
('Δήμος Τυρνάβου', '', '', 'dimos@tirnavos.gr'),
('Δήμος Ύδρας', '', '', 'dimosydr@otenet.gr'),
('Δήμος Φαιστού', '', '', 'dmiron@otenet.gr'),
('Δήμος Φαρκαδόνας', '', '', 'dimosfarkadonas@yahoo.gr'),
('Δήμος Φαρσάλων', '', '', 'mayor@dimosfarsalon.gr'),
('Δήμος Φιλιατών', '', '', 'info@filiates.gr'),
('Δήμος Φιλοθέης-Ψυχικού', '', '', 'psychiko@otenet.gr'),
('Δήμος Φλώρινας', '', '', 'dhmosflo@line.gr'),
('Δήμος Φολεγάνδρου', '', '', 'k.folegandrou@kep.gov.gr'),
('Δήμος Φούρνων Κορσεών', '', '', 'fournoi@otenet.gr'),
('Δήμος Φυλής', '', '', 'contcenter@fyli.gr'),
('Δήμος Χαϊδαρίου', '', '', 'protokollo@haidari.gr'),
('Δήμος Χαλκηδόνος', '', '', 'dimos.xalk@n3.syzefxis.gov.gr'),
('Δήμος Χάλκης', '', '', 'dhalkis@yahoo.com'),
('Δήμος Χανίων', '', '', 'dimos@chania.gr'),
('Δήμος Χερσονήσου', '', '', 'dimos@hersonisos.gr'),
('Δήμος Χίου', '', '', 'd.xios7@otenet.gr'),
('Δήμος Ωραιοκάστρου', '', '', 'info@oraiokastro.gr'),
('Δήμος Ωρωπού', '', '', 'info@oropos.gov.gr')
ON CONFLICT DO NOTHING;

